# Generated by Django 3.2.6 on 2021-08-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidVaccineStatewise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_on', models.DateField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('total_doses_administered', models.BigIntegerField(blank=True, null=True)),
                ('total_sessions_conducted', models.BigIntegerField(blank=True, null=True)),
                ('total_sites', models.IntegerField(blank=True, null=True)),
                ('first_dose_administered', models.BigIntegerField(blank=True, null=True)),
                ('second_dose_administered', models.BigIntegerField(blank=True, null=True)),
                ('male', models.IntegerField(blank=True, null=True)),
                ('female', models.IntegerField(blank=True, null=True)),
                ('transgender', models.IntegerField(blank=True, null=True)),
                ('total_covaxin_administered', models.IntegerField(blank=True, null=True)),
                ('total_coviShield_administered', models.IntegerField(blank=True, null=True)),
                ('total_sputnikV_administered', models.IntegerField(blank=True, null=True)),
                ('aefi', models.IntegerField(blank=True, null=True)),
                ('age18to45', models.IntegerField(blank=True, null=True)),
                ('age45to60', models.IntegerField(blank=True, null=True)),
                ('above60', models.IntegerField(blank=True, null=True)),
                ('total_vaccinated', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
