# Generated by Django 3.2.6 on 2021-08-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coviddata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidvaccinestatewise',
            name='above60',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='covidvaccinestatewise',
            name='aefi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='covidvaccinestatewise',
            name='age18to45',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='covidvaccinestatewise',
            name='age45to60',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='covidvaccinestatewise',
            name='total_sputnikV_administered',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='covidvaccinestatewise',
            name='total_vaccinated',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
